services:
  - type: web
    name: mindfeed-backend
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_KEY
        value: mindfeed-secret-key-2025
    autoDeploy: true
